### ISSUE TITLE
Using !weather without API key seems to crash everything

### ISSUE THREAD

**Issue by silsha** [wneessen/sotbot#9]
Someone™ used the !weather command while no API key was stored.

```
DEBUG[2021-06-02 20:20:42 +0200] Received a "!weather" command from lutoma     action=bot.CommandHandler
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8de466]

goroutine 407 [running]:
github.com/vascocosta/owm.(*Client).WeatherByName(...)
        /home/silsha/go/pkg/mod/github.com/vascocosta/owm@v0.0.0-20150101012210-5dc4adf0c67c/owm.go:287
github.com/wneessen/sotbot/handler.GetCurrentWeather(0x0, 0xc00053ec50, 0x1, 0x1, 0xc000111d08, 0x2, 0x2, 0x0)
        /home/silsha/sotbot/handler/owm_current_weather.go:27 +0x1c6
github.com/wneessen/sotbot/bot.(*Bot).CommandHandler(0xc0001c73b0, 0xc0000d6900, 0xc000010290)
        /home/silsha/sotbot/bot/command_handler.go:380 +0x29b1
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xc0006ae340, 0xc0000d6900, 0xa289c0, 0xc000010290)
        /home/silsha/go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.2/eventhandlers.go:497 +0x4b
created by github.com/bwmarrin/discordgo.(*Session).handle
        /home/silsha/go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.2/event.go:171 +0x111
```

**Comment by wneessen** [comment]
Thanks for the report. 

Fixed in https://github.com/wneessen/sotbot/commit/3f99a66c1e79cb83af01060e941aa1131df4885a
